name: busca-rag

services:
  web:
    build: .
    container_name: busca_rag_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      # Conecta na URL do banco oficial que roda lá no container da N2
      - "DATABASE_URL=postgres://yago_user:password123@analise_json_nfe_db:5432/cashflow_db"
    networks:
      - analise-json-nfe_default

networks:
  analise-json-nfe_default:
    external: true